Repository RafaelGB/obsidian-db-folder, pull requests merged in 2022-09, with the labels that each got.

#439 Imed docu branch
  docs/docs/features/Properties.md
Labels: documentation

#440 Add flex wrap to css class
  styles.css
Labels: Visual

#438 268 and or filter selector
  package.json
  src/cdm/ComponentsModel.ts
  src/cdm/SettingsModel.ts
  src/components/modals/filters/handlers/AddNewFilterHandler.tsx
  src/components/modals/filters/handlers/AtomicFilterComponent.tsx
  src/components/modals/filters/handlers/ConditionSelectorComponent.tsx
  src/components/modals/filters/handlers/DataviewFiltersComponent.tsx
  src/components/modals/filters/handlers/ExistedColumnSelectorComponent.tsx
  src/components/modals/filters/handlers/FilterGroupHandler.tsx
  src/components/modals/filters/handlers/FiltersHelper.ts
  src/components/modals/filters/handlers/GroupFilterComponent.tsx
  src/components/modals/filters/handlers/OperatorSelectorComponent.tsx
  src/components/modals/filters/handlers/ValueFilterComponent.tsx
  src/components/portals/DataviewFiltersPortal.tsx
  src/helpers/Constants.ts
  src/helpers/TableFiltersHelper.ts
  src/helpers/VaultManagement.ts
  src/parsers/RowDatabaseFieldsToFile.ts
  src/parsers/handlers/marshall/MarshallFiltersHandler.ts
  src/parsers/handlers/unmarshall/UnmarshallFiltersHandler.ts
  src/services/DatabaseInfo.ts
  src/services/DataviewService.ts
  src/services/EditEngineService.ts
  src/services/FileManagerService.ts
Labels: epic enhancement

#434 feat: nested subfolder grouping
  src/__tests__/sanitize-path.ts
  src/cdm/SettingsModel.ts
  src/components/HeaderMenu.tsx
  src/components/headerActions/handlers/buttons/RemoveColumnHandlerAction.tsx
  src/helpers/Constants.ts
  src/helpers/FileManagement.ts
  src/helpers/VaultManagement.ts
  src/services/FileGroupingService.ts
  src/settings/ColumnsSection.ts
  src/settings/handlers/columns/GroupFolderColumnDropDownHandler.ts
  src/settings/handlers/columns/GroupFolderColumnTextInputHandler.ts
  src/stateManagement/data/handlers/UpdateCellHandlerAction.ts
Labels: enhancement

#455 PR of 454
  .vscode/settings.json
  docs/docs/changelog.md
  src/cdm/SettingsModel.ts
  src/components/NavBar.tsx
  src/components/modals/filters/handlers/FiltersHelper.ts
  src/components/modals/filters/handlers/GroupFilterComponent.tsx
  src/components/modals/filters/handlers/LabelComponent.tsx
  src/components/modals/newColumn/handlers/AddEmptyColumnHandler.ts
  src/components/reducers/QuickFilters.tsx
  src/helpers/Constants.ts
  src/parsers/handlers/unmarshall/UnmarshallFiltersHandler.ts
  src/services/FileGroupingService.ts
  src/stateManagement/data/handlers/AddRowHandlerAction.ts
Labels: enhancement
